"""initial

Revision ID: 6f6341623e8c
Revises: 
Create Date: 2026-07-07 10:38:04.148851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f6341623e8c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('google_id', sa.Text(), nullable=False),
    sa.Column('google_access_token', sa.Text(), nullable=True),
    sa.Column('google_refresh_token', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('google_id')
    )
    op.create_table('coursework',
    sa.Column('coursework_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('google_coursework_id', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('coursework_id')
    )
    op.create_table('report',
    sa.Column('report_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('coursework_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['coursework_id'], ['coursework.coursework_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('report_id'),
    sa.UniqueConstraint('coursework_id')
    )
    op.create_table('submission',
    sa.Column('submission_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('coursework_id', sa.Integer(), nullable=False),
    sa.Column('google_submission_id', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['coursework_id'], ['coursework.coursework_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('submission_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('submission')
    op.drop_table('report')
    op.drop_table('coursework')
    op.drop_table('users')
    # ### end Alembic commands ###
