# Import all models here so that SQLAlchemy and Alembic can discover them
# Any model not imported here won't be included in autogenerated migrations
from app.models.user import User
from app.models.coursework import Coursework
from app.models.submission import Submission
from app.models.report import Report
